# =====================================================================
# AutoIndex - ui/styles.py
# =====================================================================

CUSTOM_CSS = """
<style>
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');

html, body, [class*="css"] {
    font-family: 'Plus Jakarta Sans', sans-serif !important;
    color: #1E1B4B !important;
}

/* Background dot pattern */
.stApp {
    background-color: #EEF2FF !important;
    background-image: radial-gradient(#A5B4FC 1.2px, transparent 1.2px) !important;
    background-size: 26px 26px !important;
}

#MainMenu, footer, header { visibility: hidden; }
.stDeployButton { display: none !important; }
[data-testid="stToolbar"] { display: none !important; }

.main .block-container {
    max-width: 860px !important;
    padding-top: 1.5rem !important;
    padding-bottom: 5rem !important;
}

/* ════ HEADER ═══════════════════════════════════════════════ */
.app-header {
    background: linear-gradient(135deg, #4338CA 0%, #6D28D9 55%, #0F766E 100%);
    border-radius: 18px;
    padding: 1.8rem 2rem;
    margin-bottom: 1.5rem;
    display: flex;
    align-items: center;
    gap: 18px;
    box-shadow: 0 8px 30px rgba(79,70,229,.30);
    position: relative;
    overflow: hidden;
}
.app-header::before {
    content:''; position:absolute;
    width:220px; height:220px;
    background:rgba(255,255,255,.07); border-radius:50%;
    top:-90px; right:50px; pointer-events:none;
}
.app-header::after {
    content:''; position:absolute;
    width:130px; height:130px;
    background:rgba(255,255,255,.05); border-radius:50%;
    bottom:-55px; right:5px; pointer-events:none;
}
.app-header .logo {
    width:54px; height:54px;
    background:rgba(255,255,255,.15);
    border:2px solid rgba(255,255,255,.25);
    border-radius:14px;
    display:flex; align-items:center; justify-content:center;
    font-size:26px; flex-shrink:0; z-index:1;
}
.app-header h1 {
    font-size:1.65rem !important; font-weight:800 !important;
    margin:0 !important; padding:0 !important;
    color:#FFFFFF !important; line-height:1.15 !important;
    letter-spacing:-0.02em !important; z-index:1;
}
.app-header p {
    font-size:0.84rem !important; color:rgba(255,255,255,.82) !important;
    margin:5px 0 0 !important; z-index:1;
}

/* ════ CARD WRAPPER (via st.container(border=True)) ══════════ */
/* Target the border wrapper generated by Streamlit that contains our step-label */
[data-testid="stElementContainer"] > div:has(> [data-testid="stVerticalBlock"] .step-label),
.element-container > div:has(> [data-testid="stVerticalBlock"] .step-label),
[data-testid="stVerticalBlock"]:has(> .element-container .step-label) {
    background-color: #FFFFFF !important;
    border-radius: 16px !important;
    border: none !important;
    border-left: 5px solid #4F46E5 !important;
    padding: 1.5rem 1.75rem !important;
    margin-bottom: 1rem !important;
    box-shadow: 0 4px 20px rgba(79,70,229,.08) !important;
}

[data-testid="stElementContainer"] > div:has(> [data-testid="stVerticalBlock"] .step-label) p,
[data-testid="stElementContainer"] > div:has(> [data-testid="stVerticalBlock"] .step-label) span,
[data-testid="stElementContainer"] > div:has(> [data-testid="stVerticalBlock"] .step-label) label,
[data-testid="stElementContainer"] > div:has(> [data-testid="stVerticalBlock"] .step-label) div,
.element-container > div:has(> [data-testid="stVerticalBlock"] .step-label) p,
.element-container > div:has(> [data-testid="stVerticalBlock"] .step-label) span,
.element-container > div:has(> [data-testid="stVerticalBlock"] .step-label) label,
.element-container > div:has(> [data-testid="stVerticalBlock"] .step-label) div {
    color: #1E1B4B; /* Ensure text inside is visible and dark */
}

/* ════ STEP LABEL ════════════════════════════════════════════ */
.step-label {
    display:inline-flex; align-items:center; gap:7px;
    font-size:0.68rem; font-weight:700; letter-spacing:.1em;
    text-transform:uppercase; color:#4F46E5;
    background:#EEF2FF; border:1.5px solid #C7D2FE;
    padding:3px 11px 3px 4px; border-radius:20px; margin-bottom:0.65rem;
}
.step-label .num {
    width:22px; height:22px;
    background:linear-gradient(135deg,#4F46E5,#7C3AED);
    color:#fff; border-radius:50%;
    display:inline-flex; align-items:center; justify-content:center;
    font-size:0.68rem; font-weight:800; flex-shrink:0;
}
.step-label .num.done { background:linear-gradient(135deg,#059669,#10B981); }
.step-title {
    font-size:1.08rem !important; font-weight:700 !important;
    margin:0 0 0.3rem !important; color:#1E1B4B !important;
}
.step-desc { font-size:0.84rem; color:#6B7280; margin:0 0 1rem; line-height:1.6; }

/* ════ FILE BADGE ════════════════════════════════════════════ */
.file-badge {
    display:inline-flex; align-items:center; gap:10px;
    background:#DCFCE7; color:#065F46;
    border:1.5px solid #86EFAC; border-radius:10px;
    padding:8px 16px; font-size:0.83rem; font-weight:600; margin-top:10px;
}

/* ════ FILE UPLOADER ═════════════════════════════════════════ */
/* Hapus background hitam, ganti dengan terang */
[data-testid="stFileUploader"] > div,
[data-testid="stFileUploader"] > div > div {
    background: #F0F4FF !important;
    border-radius: 12px !important;
}
[data-testid="stFileUploaderDropzone"] {
    background: #F0F4FF !important;
    border: 2px dashed #818CF8 !important;
    border-radius: 12px !important;
    padding: 1rem !important;
    transition: all .2s !important;
}
[data-testid="stFileUploaderDropzone"]:hover {
    background: #EEF2FF !important;
    border-color: #4F46E5 !important;
}
/* Teks instruksi */
[data-testid="stFileUploaderDropzoneInstructions"] span {
    color: #4338CA !important;
    font-weight: 600 !important;
}
[data-testid="stFileUploaderDropzoneInstructions"] small {
    color: #818CF8 !important;
}
/* Tombol Browse */
[data-testid="stFileUploaderDropzone"] button {
    background: #4F46E5 !important;
    color: #fff !important;
    border: none !important;
    border-radius: 8px !important;
    font-weight: 600 !important;
    font-family: 'Plus Jakarta Sans', sans-serif !important;
}
/* File yang sudah diupload — hilangkan background hitam */
[data-testid="stFileUploader"] li,
[data-testid="stFileUploaderFile"] {
    background: #EEF2FF !important;
    border: 1px solid #C7D2FE !important;
    border-radius: 8px !important;
    color: #1E1B4B !important;
}
[data-testid="stFileUploaderFile"] span,
[data-testid="stFileUploaderFile"] small {
    color: #4338CA !important;
}
/* Icon file */
[data-testid="stFileUploaderFile"] svg { color: #4F46E5 !important; }

/* ════ BUTTONS ═══════════════════════════════════════════════ */
.stButton > button {
    background: linear-gradient(135deg,#4F46E5 0%,#7C3AED 100%) !important;
    color: #FFFFFF !important; border: none !important;
    border-radius: 10px !important; padding: 0.6rem 1.8rem !important;
    font-family: 'Plus Jakarta Sans',sans-serif !important;
    font-size: 0.88rem !important; font-weight: 700 !important;
    box-shadow: 0 4px 14px rgba(79,70,229,.35) !important;
    transition: all .2s ease !important;
}
.stButton > button:hover {
    box-shadow: 0 7px 22px rgba(79,70,229,.45) !important;
    transform: translateY(-2px) !important;
}
.stButton > button:disabled {
    background: #E2E8F0 !important; color: #94A3B8 !important;
    box-shadow: none !important; transform: none !important;
}
.stDownloadButton > button {
    background: linear-gradient(135deg,#0D9488 0%,#059669 100%) !important;
    color: #FFFFFF !important; border: none !important;
    border-radius: 10px !important; padding: 0.6rem 1.8rem !important;
    font-family: 'Plus Jakarta Sans',sans-serif !important;
    font-size: 0.88rem !important; font-weight: 700 !important;
    box-shadow: 0 4px 14px rgba(13,148,136,.35) !important;
    transition: all .2s !important;
}
.stDownloadButton > button:hover {
    box-shadow: 0 7px 22px rgba(13,148,136,.45) !important;
    transform: translateY(-2px) !important;
}

/* ════ SLIDER ════════════════════════════════════════════════ */
[data-testid="stSlider"] [role="slider"] {
    background: #4F46E5 !important; border-color: #4F46E5 !important;
}

/* ════ DATA EDITOR ═══════════════════════════════════════════ */
[data-testid="stDataEditor"] {
    border: 1.5px solid #C7D2FE !important;
    border-radius: 12px !important; overflow: hidden !important;
    box-shadow: 0 2px 10px rgba(79,70,229,.07) !important;
}

/* ════ PROGRESS BAR ══════════════════════════════════════════ */
.stProgress > div > div > div > div {
    background: linear-gradient(90deg,#4F46E5,#7C3AED) !important;
    border-radius: 6px !important;
}

/* ════ ALERTS ════════════════════════════════════════════════ */
[data-testid="stAlert"] { border-radius: 10px !important; font-size: 0.85rem !important; }

/* ════ METRICS ═══════════════════════════════════════════════ */
[data-testid="metric-container"] {
    background: linear-gradient(135deg,#EEF2FF,#F5F3FF) !important;
    border: 1.5px solid #C7D2FE !important;
    border-radius: 12px !important; padding: 14px 18px !important;
}
[data-testid="stMetricValue"] {
    font-family: 'JetBrains Mono',monospace !important;
    font-size: 1.7rem !important; font-weight: 700 !important; color: #4F46E5 !important;
}
[data-testid="stMetricLabel"] {
    font-size: 0.76rem !important; font-weight: 700 !important;
    color: #6B7280 !important; text-transform: uppercase !important; letter-spacing: .07em !important;
}

/* ════ FOOTER ════════════════════════════════════════════════ */
.app-footer {
    text-align:center; font-size:0.76rem; color:#9CA3AF;
    margin-top:3rem; padding:1.25rem 0 0.5rem;
    border-top:1.5px dashed #C7D2FE; letter-spacing:.03em;
}
.app-footer strong { color:#4F46E5; font-weight:700; }
</style>
"""


def inject_css():
    import streamlit as st
    st.markdown(CUSTOM_CSS, unsafe_allow_html=True)

def apply_custom_js():
    import streamlit.components.v1 as components
    components.html("""
    <script>
    // Run after a slight delay to ensure Streamlit DOM is fully rendered
    setTimeout(() => {
        const parent = window.parent.document;
        const labels = parent.querySelectorAll('.step-label');
        labels.forEach(label => {
            // Find the closest border wrapper or vertical block that acts as the card container
            let container = label.closest('[data-testid="stVerticalBlockBorderWrapper"]');
            if (!container) {
                // Fallback for different Streamlit versions
                let stBlock = label.closest('[data-testid="stVerticalBlock"]');
                if (stBlock && stBlock.parentElement && stBlock.parentElement.className.includes('st-emotion-cache')) {
                    container = stBlock.parentElement;
                } else {
                    container = stBlock;
                }
            }
            
            if (container) {
                container.style.setProperty('background-color', '#FFFFFF', 'important');
                container.style.setProperty('border', 'none', 'important');
                container.style.setProperty('border-left', '5px solid #4F46E5', 'important');
                container.style.setProperty('border-radius', '16px', 'important');
                container.style.setProperty('padding', '1.5rem 1.75rem', 'important');
                container.style.setProperty('margin-bottom', '1rem', 'important');
                container.style.setProperty('box-shadow', '0 4px 20px rgba(79,70,229,.08)', 'important');
            }
        });
    }, 100);
    </script>
    """, height=0, width=0)