name: Deploy Streamlit

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /www/wwwroot/Auto-Index
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart streamlit-autoindex